---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: win-webserver
  labels:
    app: win-webserver
spec:
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
    spec:
      hostNetwork: true
      initContainers:
      - name: install-cni
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command:
        - powershell.exe
        args:
        - -command
        - cp /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      containers:
      - name: windowswebserver
        image: stefanscherer/webserver-windows:latest
        env:
        - name: PORT
          value: "80"
        ports:
        - name: http
          containerPort: 80
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: "windows"
        operator: "Equal"
        value: "2019"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
      - name: cni
        hostPath:
          path: /ProgramData/Kubernetes/cni/config/
