kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-windows-cfg
  labels:
    tier: node
    app: flannel
data:
  # need to fix 10.74.47.0/24 -- hardcoded to host ip cidr
  # buncha other stuff hardcoded
  cni-conf.json: |
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true,
            "type": "win-overlay",
            "dns": {
              "nameservers": ["10.100.200.10"],
              "search": ["svc.cluster.local"]
            },
            "policies": [
              {
                "Name": "EndpointPolicy",
                "Value": {
                  "Type": "OutBoundNAT",
                  "ExceptionList": [
                    "10.244.0.0/16",
                    "10.100.200.0/24",
                    "172.17.0.0/24"
                  ]
                }
              },
              {
                "Name": "EndpointPolicy",
                "Value": {
                  "Type": "ROUTE",
                  "DestinationPrefix": "10.100.200.0/24",
                  "NeedEncap": true
                }
              },
              {
                "Name": "EndpointPolicy",
                "Value": {
                  "Type": "ROUTE",
                  "DestinationPrefix": "172.17.0.25/32",
                  "NeedEncap": true
                }
              }
            ]
          }
        }
      ]
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-windows-amd64
  labels:
    tier: node
    app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - windows
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      hostNetwork: true
      serviceAccountName: flannel
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-flannel
        image: gcr.io/cf-london-servces-k8s/windows-images/flannel:latest
        command:
        - powershell
        args:
        - -command
        - mkdir -force /host/etc/cni/net.d; cp -force /etc/kube-flannel/cni-conf.json /host/etc/cni/net.d/10-flannel.conflist; mkdir -force /host/opt/cni/bin; cp -force -recurse /cni/* /host/opt/cni/bin; mkdir -force /host/flannel; cp -force /flannel/flanneld.exe /host/flannel/flanneld.exe; cp -force /kube-proxy/kubeconfig.conf /host/flannel/kubeconfig.yml; mkdir -force /host/flannel/var/run/secrets/kubernetes.io/serviceaccount; cp -force /var/run/secrets/kubernetes.io/serviceaccount/* /host/flannel/var/run/secrets/kubernetes.io/serviceaccount/; wins cli process run --path C:\flannel\flanneld.exe --args "--kube-subnet-mgr --kubeconfig-file /flannel/kubeconfig.yml" --envs "POD_NAME=$env:POD_NAME POD_NAMESPACE=$env:POD_NAMESPACE"
        volumeMounts:
        - name: wins
          mountPath: \\.\pipe\rancher_wins
        - name: host
          mountPath: /host
        - name: kube-proxy
          mountPath: /kube-proxy
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      volumes:
        - name: opt
          hostPath:
            path: /opt
        - name: host
          hostPath:
            path: /
        - name: cni
          hostPath:
            path: /etc
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg
        - name: kube-proxy
          configMap:
            name: kube-proxy
        - name: wins
          hostPath:
            path: \\.\pipe\rancher_wins
            type: null
